In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/House_Rent_Dataset.csv')

In [ ]:
df.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [ ]:
df.shape

(4746, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   object
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Floor              4746 non-null   object
 5   Area Type          4746 non-null   object
 6   Area Locality      4746 non-null   object
 7   City               4746 non-null   object
 8   Furnishing Status  4746 non-null   object
 9   Tenant Preferred   4746 non-null   object
 10  Bathroom           4746 non-null   int64
 11  Point of Contact   4746 non-null   object
dtypes: int64(4), object(8)
memory usage: 445.1+ KB

In [ ]:
df.isnull().sum()

Posted On            0
BHK                  0
Rent                 0
Size                 0
Floor                0
Area Type            0
Area Locality        0
City                 0
Furnishing Status    0
Tenant Preferred     0
Bathroom             0
Point of Contact     0
dtype: int64

In [ ]:
df.columns

Index(['Posted On', 'BHK', 'Rent', 'Size', 'Floor', 'Area Type',
       'Area Locality', 'City', 'Furnishing Status', 'Tenant Preferred',
       'Bathroom', 'Point of Contact'],
      dtype='object')

In [ ]:
categorical_columns = ['Posted On', 'BHK', 'Rent', 'Size', 'Floor', 'Area Type',
       'Area Locality', 'City', 'Furnishing Status', 'Tenant Preferred',
       'Bathroom', 'Point of Contact']

for column in categorical_columns:
  print(f"Unique values for {column}: {df[column].unique()}")

Unique values for Posted On: ['2022-05-18' '2022-05-13' '2022-05-16' '2022-07-04' '2022-05-09'
 '2022-04-29' '2022-06-21' '2022-06-07' '2022-06-20' '2022-05-23'
 '2022-05-14' '2022-05-05' '2022-06-01' '2022-05-17' '2022-06-09'
 '2022-07-02' '2022-06-14' '2022-06-15' '2022-05-28' '2022-05-22'
 '2022-06-18' '2022-06-25' '2022-06-22' '2022-05-21' '2022-06-26'
 '2022-06-16' '2022-06-29' '2022-05-10' '2022-05-12' '2022-06-03'
 '2022-05-31' '2022-06-10' '2022-06-24' '2022-04-30' '2022-05-27'
 '2022-06-06' '2022-05-20' '2022-05-26' '2022-07-03' '2022-04-23'
 '2022-06-19' '2022-07-06' '2022-06-04' '2022-05-30' '2022-06-08'
 '2022-05-03' '2022-05-07' '2022-06-27' '2022-05-15' '2022-04-28'
 '2022-06-28' '2022-06-23' '2022-06-13' '2022-05-04' '2022-04-25'
 '2022-05-06' '2022-06-30' '2022-07-01' '2022-06-17' '2022-06-11'
 '2022-05-11' '2022-06-12' '2022-06-05' '2022-05-25' '2022-05-24'
 '2022-05-19' '2022-04-24' '2022-04-27' '2022-05-08' '2022-04-26'
 '2022-06-02' '2022-05-29' '2022-07-07' '2022-07-08' '2022-07-09'
 '2022-07-05' '2022-05-01' '2022-04-13' '2022-05-02' '2022-07-10'
 '2022-07-11']
Unique values for BHK: [2 1 3 6 4 5]
Unique values for Rent: [  10000   20000   17000    7500    7000    5000   26000   25000    6500
    5500    8500   40000    6000   11000    7900    9000    4000    8000
    5300   12500   15000   22000   21000    7200   12000    4600   30000
    3500   16000   14500    8200    6700   18000   35000  180000   14000
    3900    6300   13000    6800    4700    4500   17500    2200    9500
   16500   10500   50000    5200   24000    3000    3200    1500    3800
    6200    9900   36125   23000    5146   22500   34000    1800    3700
    3300   60000   65000   45000   70000   75000  160000  300000  130000
   33000   32000   49000   28000   33500   85000  270000  400000  150000
  100000   19411  190000   68000  110000   44000   43000   57000   27000
   55000   95000   80000   89000   38000  350000  170000  210000   47000
  120000   62000   42000   41000   84500  220000  310000   53000  250000
   13500   25500   45002   48000  140000  230000  600000   46000   55100
  320000   92500   29999  330000   36000   53500   61000  200000   19000
   18500   19500   90000   93000   69999 1000000   33003  450000  280000
   56000   83000   39000   15500   51000  260000   43500   77500   59000
   72000   52000   51500   98000   23500 1200000   84000  500000    9400
   94000   58000   54500   67000  380000   29500   37000   35500   90100
   77000  290000  240000   26500   54000   76000   79500   63000   28500
  360000   66000  650000  850000   34999   49500   46700   88000   78000
   74999   69000   29000   31000  700000  680000   61500   11400   11500
   32900    6900   27500    9750 3500000    8900   21500    9300   26969
   42500    4300    4800   17681   13900    7700    4750   17600    9250
   14900   20500    2000   17401   44300  530000   20200   31500   22999
   12100   24500    7600   11200   34500    5700   23999    5250   47500
   18999    4200   15723    6250   37500    6166    9800   19397   27999
   10677   32500   23382   19800    1200    5400   12333   21467    5800]
Unique values for Size: [1100  800 1000  850  600  700  250 1200  400  375  900 1286 2000  660
  650  300 1600  355  350  550  500  630  270 1500 1300 1068  150  450
  720  680  950 1800  480  435 1450  750  220   20  200  840  740  490
  751  280  120 1220  670  190  240 2200  685   44 1110  392  710 1400
  160 1250  839  230  620 1350  723  320 2160 1700  130  505 4000 1190
 1012  812  420 1750  830 1050  960  756  288  986 1330  322 3500  957
 1430 1320  475  780  570  460  530  558  175  425  721 1150 2210  675
 1880  640 1650  518  777 2308  890  888  275  424 2079  586  610  488
  722  470  410  540  932  560 3000  696 2500  715 1337  737  760  365
 2600 1783  565 1514 1080  825  360 1545  432  695 1095  790  661  330
  925 1105 1460  415  585 1755  385  628 1064  845 1915  807  380  428
 1550 1454  860  433 2700 1225 1224  305  690  635 1379  390  935  535
 3700 1208 3200  225  463 1900 1325  905  455  430  795  575  656  719
 3064 3400  980 2800  413 1850 1705 1355  340  471 1528 1030  985  806
  583  994  520 2750 2424  724 1076 2170  485  478  704  525  755  625
  370  805  742  745 1265  325  902 1233 2120 1937 5000  596 1950  510
 1260  770 3900  694 3250 1740  472  421  515  831  753 1197  880 1088
 2650  975  785 1016  444  508  623 1358 1255  955  870 1691  615  663
 1432  649  882  736 1710  555 1065  854  906 1130  495  407 1092  669
  725  999 1256  889  434 1121  937  379  920  440  582 1617  836 2046
  730  229  910 1648  820  771 1526  465 1073  310  967 1649 1560 4500
 1425 1375 1270  265  422  895 1663  377 2080  965 2100 1380  868  970
  774 1152  641  810  875  758 2880 1962  590 1120 2729 3354 1040 1403
 2608 1045 1021 1280 1680 1155 2900 3150  100 1603 1771  773  865 1840
 1159   50  990 1360 1757 1281 1221  416  976 1387 1020 1645 3276 1893
 1296 4800 1066 2150 2110 1025 1180  580  904 1252 2770  144 1005 1274
 1480 1115 1060 1278 4105 1055  894 2400 2430 1475 4341  846  110 5700
 1760 3100  775  445 2710 1768  532 1465  940 1789 1618 1374 1580 4550
 1333 1875 1660 1305 1188 2390 1788 1520 1464  180  140   75 1670   70
   60  170   48 1901  145   25  892   80   45 1125  713   54   63 1440
   55   68   65 2300   84   90  512  446  125  499   30  497   95  272
 2925  106   96  545  165 1872   40   42 2550 3800 1205   77 1027 1428
 2117 1462  674 1540  930 1210 1234 1162 1261 1145 3600 1158  898  717
 1070 2036  619  115 1725 2064 1557  917  579 1920 1002  778 1567 1113
 1175 1010  618 1651  705  901 1340 1246 1099 1530 1780 1402 1484 1140
 1525 1132 3300  786 1785  803 1975  914 1170 1435 1444 1503  966 1062
 1015 1570 1157 2792 1153  506  749 1107 1235 1415  281 6000  926 2280
  826  502  833  809 2240 1424  595 1075 2317 1109 1290  939 1610  973
 1420  843 1144 1903 1383 1912 1146  909  886 1625 1535  647 1798 2061
  919 2395 1815 2290 1473 4050 2520  242 1496  878 1956 1955 1090 3133
 2050 1160 1417 1565 1675 1135 3698 2405 1248 3115  927  562 1720  103
 8000 1730  133  192 1315 1230 4761 1970 1940  167  933 1742 1838 1960
 1275 1285 2235 1283 3455 3050 7000 1606 2352 2671 1156   67 1492 2990
 2780 1685  853 2310 1965 1834   10 3789 1422 1124 4200  214  855]
Unique values for Floor: ['Ground out of 2' '1 out of 3' '1 out of 2' 'Ground out of 1'
 'Ground out of 4' '1 out of 4' '1 out of 1' 'Ground out of 3'
 '2 out of 3' '4 out of 5' '2 out of 2' '2 out of 5' '4 out of 14'
 '3 out of 3' '5 out of 5' '4 out of 4' '7 out of 8' '2 out of 4'
 '3 out of 4' '1 out of 5' '8 out of 5' 'Ground out of 6' '2 out of 1'
 'Upper Basement out of 4' 'Ground out of 5' '3 out of 5' '11 out of 19'
 '5 out of 10' '11 out of 14' 'Lower Basement out of 2' '2 out of 7'
 '4 out of 10' '7 out of 10' '2 out of 13' '6 out of 7' '4 out of 7'
 '14 out of 14' '43 out of 78' '2 out of 8' '13 out of 18' '5 out of 12'
 '18 out of 24' '3 out of 7' '17 out of 31' '11 out of 21' '7 out of 19'
 '14 out of 23' '9 out of 20' 'Upper Basement out of 9' '19 out of 24'
 '3 out of 21' '1 out of 22' '8 out of 8' '6 out of 12' '4 out of 58'
 'Upper Basement out of 16' '60 out of 66' '34 out of 48' '5 out of 8'
 '5 out of 14' '14 out of 40' '5 out of 7' '9 out of 22' '12 out of 18'
 '26 out of 44' '1 out of 8' '25 out of 42' '25 out of 41' '53 out of 78'
 'Ground out of 7' '14 out of 20' '13 out of 20' '16 out of 23'
 '10 out of 18' '39 out of 60' '16 out of 21' '10 out of 32' '4 out of 8'
 '12 out of 24' '32 out of 41' '3 out of 30' '13 out of 21' '9 out of 29'
 '47 out of 89' '7 out of 41' '28 out of 30' '13 out of 15' '6 out of 21'
 '8 out of 16' '2 out of 6' '5 out of 19' '3 out of 11' '17 out of 42'
 '10 out of 12' '8 out of 28' '9 out of 15' '14 out of 22' '18 out of 40'
 '9 out of 17' '12 out of 45' '25 out of 35' '7 out of 15' '10 out of 16'
 'Upper Basement out of 20' '5 out of 20' 'Upper Basement out of 40'
 '5 out of 18' '34 out of 58' '4 out of 6' '20 out of 22' '12 out of 19'
 '15 out of 18' '65 out of 78' '6 out of 16' '17 out of 22' '6 out of 24'
 '40 out of 75' '19 out of 38' '15 out of 31' '11 out of 28'
 '10 out of 22' '17 out of 24' '15 out of 19' '9 out of 10' '7 out of 12'
 '8 out of 20' '11 out of 13' '9 out of 19' '37 out of 51' '6 out of 11'
 '8 out of 15' '11 out of 20' '10 out of 23' 'Upper Basement out of 10'
 '7 out of 23' '4 out of 11' '17 out of 43' '7 out of 22' '14 out of 18'
 '6 out of 10' '8 out of 12' '3 out of 18' '7 out of 7' '14 out of 58'
 '18 out of 23' '19 out of 19' '13 out of 14' '7 out of 11' '11 out of 22'
 'Upper Basement out of 30' '12 out of 14' '16 out of 31' '12 out of 13'
 '11 out of 51' '2 out of 12' '22 out of 24' '7 out of 14' '5 out of 13'
 '7 out of 21' '14 out of 21' '17 out of 25' '9 out of 14' '8 out of 27'
 '3 out of 6' '17 out of 20' '18 out of 22' '1 out of 7' '9 out of 30'
 '3 out of 8' '11 out of 26' '17 out of 27' '4 out of 12' '12 out of 16'
 '10 out of 24' '65 out of 76' '7 out of 9' '17 out of 60' '10 out of 11'
 '18 out of 25' '5 out of 11' '15 out of 17' '15 out of 23' '5 out of 17'
 '3 out of 28' '5 out of 24' '16 out of 32' '21 out of 22' '7 out of 13'
 '9 out of 12' '15 out of 32' '18 out of 27' '15 out of 16' '18 out of 45'
 '15 out of 15' '6 out of 14' '1 out of 20' '16 out of 36' '30 out of 44'
 '30 out of 37' '2 out of 9' '12 out of 22' '4 out of 9' '2 out of 22'
 '5 out of 6' '6 out of 18' '35 out of 55' '16 out of 29' '30 out of 45'
 '5 out of 9' '16 out of 25' '33 out of 42' '4 out of 16' '13 out of 23'
 '9 out of 38' '6 out of 8' '8 out of 13' '19 out of 30' '10 out of 14'
 '11 out of 24' '9 out of 16' '9 out of 31' '4 out of 15' '3 out of 9'
 '22 out of 30' '3 out of 58' '1 out of 9' '53 out of 60' '5 out of 22'
 '15 out of 22' '19 out of 21' '9 out of 40' 'Ground out of 8'
 '44 out of 75' '8 out of 17' '3 out of 14' '12 out of 31' '26 out of 42'
 '2 out of 45' '12 out of 68' '17 out of 36' '10 out of 28' '41 out of 41'
 '14 out of 68' '14 out of 17' '15 out of 20' '46 out of 76'
 '12 out of 20' '20 out of 30' '18 out of 32' '10 out of 25'
 '17 out of 29' '10 out of 31' '10 out of 15' '13 out of 16' '8 out of 10'
 '18 out of 21' '27 out of 58' '1 out of 6' '19 out of 25' '3 out of 15'
 '25 out of 43' '8 out of 14' '11 out of 12' '9 out of 21' '10 out of 13'
 '45 out of 77' '18 out of 19' '10 out of 20' '12 out of 29'
 'Lower Basement out of 18' '15 out of 24' '48 out of 68' '12 out of 42'
 '16 out of 22' '35 out of 68' '18 out of 30' '11 out of 31'
 '50 out of 75' '18 out of 26' '12 out of 27' '16 out of 20'
 '24 out of 55' '16 out of 37' 'Upper Basement out of 7' '6 out of 15'
 '11 out of 27' '11 out of 23' '3 out of 12' '14 out of 15' '23 out of 25'
 '14 out of 48' '29 out of 35' '15 out of 36' '15 out of 25'
 '15 out of 28' '3 out of 36' '8 out of 11' '6 out of 20' '23 out of 23'
 '5 out of 15' '16 out of 18' '2 out of 10' '40 out of 50' '25 out of 28'
 '12 out of 17' '34 out of 40' 'Upper Basement out of 22' '8 out of 23'
 '5 out of 21' '32 out of 59' '20 out of 32' '9 out of 18' '10 out of 37'
 '25 out of 48' '4 out of 22' '8 out of 18' '11 out of 11' '5 out of 23'
 '60 out of 77' '11 out of 18' '4 out of 20' '5 out of 16' '3 out of 13'
 '30 out of 58' '15 out of 43' '7 out of 16' '18 out of 28' '9 out of 55'
 '11 out of 25' '49 out of 55' '7 out of 27' '14 out of 27' '16 out of 27'
 '25 out of 50' '6 out of 30' '21 out of 23' '8 out of 58' '20 out of 41'
 '3 out of 62' '4 out of 13' '7 out of 17' '12 out of 21' '28 out of 39'
 '15 out of 58' '6 out of 23' '36 out of 45' '9 out of 28' '6 out of 45'
 '22 out of 52' '10 out of 19' '21 out of 58' '48 out of 54' '7 out of 28'
 '11 out of 15' '19 out of 22' '15 out of 37' '2 out of 17' '76 out of 78'
 '3 out of 10' '20 out of 27' '8 out of 36' '14 out of 33' '21 out of 21'
 '12 out of 25' '18 out of 29' '14 out of 35' '7 out of 20' '20 out of 37'
 '9 out of 35' '27 out of 27' '15 out of 60' '19 out of 33' '18 out of 20'
 '13 out of 40' '9 out of 11' '8 out of 22' '6 out of 13' '20 out of 31'
 '27 out of 45' '19 out of 20' '32 out of 46' '19 out of 85' '3 out of 23'
 '34 out of 46' '4 out of 27' '19 out of 27' '35 out of 60' '21 out of 33'
 '25 out of 52' '2 out of 24' '24 out of 24' '18 out of 33' '1 out of 10'
 '45 out of 60' '60 out of 71' '36 out of 81' '24 out of 60'
 '16 out of 38' '8 out of 45' 'Ground out of 16' '8 out of 32'
 '10 out of 10' '23 out of 40' '7 out of 18' '8 out of 19' '6 out of 17'
 '16 out of 34' 'Ground out of 12' '6 out of 9' 'Ground out of 18'
 '20 out of 25' '3 out of 22' '9 out of 32' '26 out of 32' '17 out of 18'
 '24 out of 25' '19 out of 26' '17 out of 19' '1 out of 13' '14 out of 30'
 '8 out of 9' '3 out of 17' 'Lower Basement out of 3' '12 out of 23'
 'Ground out of 9' '1 out of 24' '1 out of 12' '3' 'Ground' '15 out of 29'
 '20 out of 20' '14 out of 29' 'Lower Basement out of 1' '13 out of 17'
 '1 out of 14' 'Upper Basement out of 2' '2 out of 14' '24 out of 31'
 '2 out of 32' '2 out of 16' '9 out of 13' '1 out of 11' '6 out of 29'
 '9 out of 9' '28 out of 31' '1 out of 15' 'Ground out of 14'
 '2 out of 11' '19 out of 31' '1 out of 16' '25 out of 32' '11 out of 16'
 '11 out of 17' 'Upper Basement out of 3' '4 out of 24' '1 out of 19'
 '7 out of 30' '16 out of 19' 'Upper Basement out of 5' 'Ground out of 13'
 '2 out of 25' '23 out of 30' '4 out of 30' '13 out of 25' '23 out of 35'
 'Ground out of 10' '5 out of 34' '20 out of 35' '1' '4 out of 31'
 '4 out of 26' '24 out of 33' '4 out of 17' '1 out of 35' '11 out of 35'
 'Ground out of 15' 'Ground out of 27' '15 out of 30' '12 out of 30'
 '23 out of 34']
Unique values for Area Type: ['Super Area' 'Carpet Area' 'Built Area']
Unique values for Area Locality: ['Bandel' 'Phool Bagan, Kankurgachi' 'Salt Lake City Sector 2' ...
 'BN Reddy Nagar' 'Godavari Homes, Quthbullapur' 'Manikonda, Hyderabad']
Unique values for City: ['Kolkata' 'Mumbai' 'Bangalore' 'Delhi' 'Chennai' 'Hyderabad']
Unique values for Furnishing Status: ['Unfurnished' 'Semi-Furnished' 'Furnished']
Unique values for Tenant Preferred: ['Bachelors/Family' 'Bachelors' 'Family']
Unique values for Bathroom: [ 2  1  3  5  4  6  7 10]
Unique values for Point of Contact: ['Contact Owner' 'Contact Agent' 'Contact Builder']

In [ ]:
from sklearn.preprocessing import LabelEncoder
categorical_columns= ['Posted On', 'BHK', 'Rent', 'Size', 'Floor', 'Area Type',
       'Area Locality', 'City', 'Furnishing Status', 'Tenant Preferred',
       'Bathroom', 'Point of Contact']
label_encoders = {}
for column in categorical_columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

df[categorical_columns] = scaler.fit_transform(df[categorical_columns])

In [ ]:
df.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,0.3250,0.2,0.231405,0.543974,0.949896,1.0,0.098926,0.8,1.0,0.5,0.142857,1.0
1,0.2625,0.2,0.376033,0.363192,0.029228,1.0,0.683527,0.8,0.5,0.5,0.000000,1.0
2,0.3000,0.2,0.322314,0.491857,0.029228,1.0,0.787825,0.8,0.5,0.5,0.000000,1.0
3,0.9125,0.2,0.231405,0.363192,0.020877,1.0,0.235452,0.8,1.0,0.5,0.000000,1.0
4,0.2125,0.2,0.165289,0.395765,0.020877,0.5,0.846016,0.8,1.0,0.0,0.000000,1.0

In [ ]:
# prompt: calculate neural network with builtin function using relu also give comments aslo divide into train and test  using tensorflow

import tensorflow as tf
from sklearn.model_selection import train_test_split

# Assuming 'Rent' is the target variable
X = df.drop('Rent', axis=1)  # Features
y = df['Rent']  # Target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the model
model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # Input layer with ReLU activation
    keras.layers.Dense(32, activation='relu'),  # Hidden layer with ReLU activation
    keras.layers.Dense(1,activation='linear')  # Output layer (no activation for regression)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')  # Use appropriate loss for regression

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32)  # Adjust epochs and batch size as needed

# Evaluate the model
loss = model.evaluate(X_test, y_test)
print("Mean Squared Error on Test Set:", loss)

Epoch 1/50

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0411
Epoch 2/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0130
Epoch 3/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0126
Epoch 4/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0124
Epoch 5/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0117
Epoch 6/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0107
Epoch 7/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0113
Epoch 8/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0114
Epoch 9/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0104
Epoch 10/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0109
Epoch 11/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0099
Epoch 12/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0099
Epoch 13/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0098
Epoch 14/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0096
Epoch 15/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0091
Epoch 16/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0093
Epoch 17/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0088
Epoch 18/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0088
Epoch 19/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0094
Epoch 20/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0086
Epoch 21/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0079
Epoch 22/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0083
Epoch 23/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0086
Epoch 24/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0081
Epoch 25/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0079
Epoch 26/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0078
Epoch 27/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0082
Epoch 28/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0078
Epoch 29/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0077
Epoch 30/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0086
Epoch 31/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0078
Epoch 32/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0081
Epoch 33/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0071
Epoch 34/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0074
Epoch 35/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0075
Epoch 36/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0074
Epoch 37/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0076
Epoch 38/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0080
Epoch 39/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0076
Epoch 40/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0074
Epoch 41/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0075
Epoch 42/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0075
Epoch 43/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0070
Epoch 44/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0074
Epoch 45/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0069
Epoch 46/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0072
Epoch 47/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0077
Epoch 48/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0070
Epoch 49/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0072
Epoch 50/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0069
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0089
Mean Squared Error on Test Set: 0.008906635455787182

In [ ]:

from sklearn.metrics import mean_absolute_percentage_error
y_pred = model.predict(X_test)
mape = mean_absolute_percentage_error(y_test, y_pred)
print("MAPE:", mape)

30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
MAPE: 0.28666961217571374